id: I4188A2C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:04:37+00:00'
last_modified: '2022-06-07T18:48:00.835518+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN561
  title: གདན་ས་གནས་ནང་དགོན་གྱི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    540C:
      image_group_id: I3CN4031
      title: ''
      total_pages: 66
      order: 1
      base_file: 540C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
